version: '3'

services:

  zookeeper:
    image: streamnative/sn-pulsar:2.10.1.4
    container_name: zookeeper
    hostname: zookeeper
    command: >
      bash -c "bin/apply-config-from-env.py conf/zookeeper.conf &&
      exec bin/pulsar zookeeper"
    environment:
      PULSAR_PREFIX_clientPortAddress: zookeeper
      PULSAR_PREFIX_clientPort: 2181
    healthcheck:
      interval: 5s
      retries: 20
      test: echo ruok | nc zookeeper 2181

  init-cluster:
    image: streamnative/sn-pulsar:2.10.1.4
    container_name: init-cluster
    hostname: init-cluster
    depends_on:
      zookeeper:
        condition: service_healthy
    command: >
      bash -c "bin/pulsar initialize-cluster-metadata -c pulsar-cluster -zk zookeeper:2181 -cs zookeeper:2181 -uw http://pulsar-cluster-pulsar-1:8080"

  bookie:
    image: streamnative/sn-pulsar:2.10.1.4
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
    depends_on:
      zookeeper:
        condition: service_healthy
      init-cluster:
        condition: service_completed_successfully
    command: >
      bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf &&
      exec bin/bookkeeper bookie"
    environment:
      PULSAR_PREFIX_zkServers: zookeeper:2181
      PULSAR_PREFIX_useHostNameAsBookieID: "true"
      PULSAR_PREFIX_bookiePort: 3181
    healthcheck:
      interval: 5s
      retries: 20
      test: echo ruok | nc localhost 3181

  broker:
    image: streamnative/sn-pulsar:2.10.1.4
    container_name: pulsar-1
    hostname: pulsar-1
    depends_on:
      - bookie
    command: >
      bash -c "bin/apply-config-from-env.py conf/broker.conf &&
      exec bin/pulsar broker"
    environment:
      PULSAR_PREFIX_messagingProtocols: amqp
      PULSAR_PREFIX_zookeeperServers: zookeeper:2181
      PULSAR_PREFIX_configurationStoreServers: zookeeper:2181
      PULSAR_PREFIX_clusterName: pulsar-cluster
      PULSAR_PREFIX_managedLedgerDefaultEnsembleSize: 1
      PULSAR_PREFIX_managedLedgerDefaultWriteQuorum: 1
      PULSAR_PREFIX_managedLedgerDefaultAckQuorum: 1
      PULSAR_PREFIX_amqpListeners: amqp://pulsar-1:5672
    ports:
      - 6650:6650 # Pulsar Binary
      - 8080:8080
      - 5672:5672 # AMQP
    healthcheck:
      interval: 5s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8080/admin/v2/clusters/pulsar-cluster

networks:
  default:
    name: amqp-protocol-pulsar
